title: 김현준
logo: /assets/img/hyunjoon-kim.png
email: jun9906@naver.com
description: N/A
url: https://only-joon.github.io
favicon: true
# color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-gist
  - jemoji

platforms:
  - name: Phone
    icon: <i class="fa-solid fa-phone"></i>
    link: tel:+821062370565
    content: 010-6237-0565
  - name: Email
    icon: <i class="fa-regular fa-envelope"></i>
    link: mailto:jun9906@naver.com
    content: jun9906@naver.com

navigation:
  - name: About Me
    link: .
    # sublist:
    #   - name: Image
    #     link: ./index.html#small-image
  # - name: Projects
  #   link: ./projects.html
